### ISSUE TITLE
[NEED HELP]: How to make xiaoxiaoflood script compatible with your loader?

### ISSUE THREAD

**Issue by quivenda** [benzBrake/FirefoxCustomize#15]
### 你在用什么浏览器

Firefox

### 浏览器版本号

102.8.0esr (64-bit)

### 你在用什么 UC 环境(引导器)

没有使用

### 有什么问题

For example, I'm using styloaix from xiaoxiaoflood, but with your loader, the icon did not show up but the style still working. I was also using this script 000-xiaoxiaoflood.uc.js from your GitHub.

Also, how to make extensions from xiaoxiaoflood showing current uc.js? I like it more because easy to disable and enable scripts instead of opening about:addons

screenshot:

[https://i.imgur.com/QS8F7yF.png](https://i.imgur.com/QS8F7yF.png)

Thanks.

**Comment by benzBrake** [comment]
000-xiaoxiaoflood.ucj.js was initially used to be compatible with extensionsOptionsMenu.uc.js, it's development has been discontinued since I have found a version that works for alice0775's loader, 
My loader is based on alice0775's environment, you can use [rebuild_userChrome.js](https://github.com/alice0775/userChrome.js/blob/master/100/rebuild_userChrome.uc.js) from his repository.
As for styloaix.uc.js There's a self usage version here.
[styloaix.zip](https://github.com/benzBrake/FirefoxCustomize/files/10888463/styloaix.zip)
